//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrainWaves.Resources.Strings {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BrainWaves.Resources.Strings.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ApplicationNeedPermissionText {
            get {
                return ResourceManager.GetString("ApplicationNeedPermissionText", resourceCulture);
            }
        }
        
        internal static string AutomaticServiceChoosing {
            get {
                return ResourceManager.GetString("AutomaticServiceChoosing", resourceCulture);
            }
        }
        
        internal static string BLEData {
            get {
                return ResourceManager.GetString("BLEData", resourceCulture);
            }
        }
        
        internal static string CharacteristicReceiveUUIDLabel {
            get {
                return ResourceManager.GetString("CharacteristicReceiveUUIDLabel", resourceCulture);
            }
        }
        
        internal static string CharacteristicSendUUIDLabel {
            get {
                return ResourceManager.GetString("CharacteristicSendUUIDLabel", resourceCulture);
            }
        }
        
        internal static string Charts {
            get {
                return ResourceManager.GetString("Charts", resourceCulture);
            }
        }
        
        internal static string ConnectText {
            get {
                return ResourceManager.GetString("ConnectText", resourceCulture);
            }
        }
        
        internal static string EmptyText {
            get {
                return ResourceManager.GetString("EmptyText", resourceCulture);
            }
        }
        
        internal static string ErrorConnectingBLE {
            get {
                return ResourceManager.GetString("ErrorConnectingBLE", resourceCulture);
            }
        }
        
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        internal static string ExportToExcell {
            get {
                return ResourceManager.GetString("ExportToExcell", resourceCulture);
            }
        }
        
        internal static string FindDevice {
            get {
                return ResourceManager.GetString("FindDevice", resourceCulture);
            }
        }
        
        internal static string LanguageENG {
            get {
                return ResourceManager.GetString("LanguageENG", resourceCulture);
            }
        }
        
        internal static string LanguagePL {
            get {
                return ResourceManager.GetString("LanguagePL", resourceCulture);
            }
        }
        
        internal static string PerrmisionRequiredTitle {
            get {
                return ResourceManager.GetString("PerrmisionRequiredTitle", resourceCulture);
            }
        }
        
        internal static string ScanButtonText {
            get {
                return ResourceManager.GetString("ScanButtonText", resourceCulture);
            }
        }
        
        internal static string ServiceUUIDLabel {
            get {
                return ResourceManager.GetString("ServiceUUIDLabel", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string StopScanningText {
            get {
                return ResourceManager.GetString("StopScanningText", resourceCulture);
            }
        }
        
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        internal static string GoBackText {
            get {
                return ResourceManager.GetString("GoBackText", resourceCulture);
            }
        }
        
        internal static string BleOff {
            get {
                return ResourceManager.GetString("BleOff", resourceCulture);
            }
        }
        
        internal static string BleUnavailable {
            get {
                return ResourceManager.GetString("BleUnavailable", resourceCulture);
            }
        }
        
        internal static string SamplingFreq {
            get {
                return ResourceManager.GetString("SamplingFreq", resourceCulture);
            }
        }
        
        internal static string TimeToReadMindInMin {
            get {
                return ResourceManager.GetString("TimeToReadMindInMin", resourceCulture);
            }
        }
        
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        internal static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        internal static string ScanningMessage {
            get {
                return ResourceManager.GetString("ScanningMessage", resourceCulture);
            }
        }
        
        internal static string ExportingToExcellMessage {
            get {
                return ResourceManager.GetString("ExportingToExcellMessage", resourceCulture);
            }
        }
        
        internal static string SettingUpChartsMessage {
            get {
                return ResourceManager.GetString("SettingUpChartsMessage", resourceCulture);
            }
        }
        
        internal static string DisconnectingMessage {
            get {
                return ResourceManager.GetString("DisconnectingMessage", resourceCulture);
            }
        }
        
        internal static string GettingCharacteristicMessage {
            get {
                return ResourceManager.GetString("GettingCharacteristicMessage", resourceCulture);
            }
        }
        
        internal static string SendingMessage {
            get {
                return ResourceManager.GetString("SendingMessage", resourceCulture);
            }
        }
        
        internal static string ExcellProcessing {
            get {
                return ResourceManager.GetString("ExcellProcessing", resourceCulture);
            }
        }
    }
}
